server:
  port: 8090
spring:
  data:
    mongodb:
      authentication-database: admin
      database: customer
      host: localhost
      password: mypassword
      port: 27017
      username: ganesh